language: python
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - pip install pip -U
  - pip install pytest -U
  - pip install codecov -U
  - pip install pytest-cov -U
install:
  - travis_retry pip install -e .
script: 
  - travis_wait pytest --doctest-modules --cov-config .coveragerc --cov-report html --cov=ordered_set test.py
    
after_success: 
  - codecov 
cache: 
    apt: true
    directories:
        - $HOME/.pip-cache

